
<?php 
if(Mage::getSingleton('customer/session')->isLoggedIn()):
	$name = Mage::getSingleton('customer/session')->getCustomer()->getName();
endif;
?>
<?php include("pgconfig.php"); ?>
<html>
<head>
	<title>ACCOSA PG - Test Merchant - PHP</title>
</head>
<?php 
$transactionTypeCode=$_POST["transaction_type_code"];
$installments=$_POST["installments"];
$transactionId=$_POST["transaction_id"];

$amount=$_POST["amount"];
$exponent=$_POST["exponent"];
$currencyCode=$_POST["currency_code"];
$merchantReferenceNo=$_POST["merchant_reference_no"];

$status=$_POST["status"];
$eci=$_POST["3ds_eci"];
$pgErrorCode=$_POST["pg_error_code"];

$pgErrorDetail=$_POST["pg_error_detail"];
$pgErrorMsg=$_POST["pg_error_msg"];

$messageHash=$_POST["message_hash"];


$messageHashBuf=$pgInstanceId."|".$merchantId."|".$transactionTypeCode."|".$installments."|".$transactionId."|".$amount."|".$exponent."|".

$currencyCode."|".$merchantReferenceNo."|".$status."|".$eci."|".$pgErrorCode."|".$hashKey."|";

$messageHashClient = "13:".base64_encode(sha1($messageHashBuf, true));

$hashMatch=false;

if ($messageHash==$messageHashClient){
  $hashMatch=true;
} else {
  $hashMatch=false;
} 
?>
<body topmargin="0" leftmargin="0">
<br />
<center>
<h3>Transaction Report</h3>
	<table>

		
			
			<tr>
				<td align="left" colspan="2">
				
				<?php
				if("50020"==$status) {
					?><p><span  style="color: #009900;font-weight: bold;">Your payment is successful. </span><br />
  Thank you for your order with Supersavings.lk - Save every moment.
  Your order ID is: <? echo $merchantReferenceNo;?>
  
  Wow. seems everything good and we will dispatch your products with in 24 hours.
  
  If you have any queries with your order, please speak to our customer services on: 112 508 090 </p><?php
				} else  {
					?>

				<p  style="color: #FF0000;font-weight: bold;">Sorry your payment is unsuccessful. .</p>
<p>Please use a different debit or credit card. For support please speak to our customer services on: 112 508 090.<br />
  Thanks.</p><?
				}
			?>
				</td>
				
			</tr>

			<!--<tr>
				<td align="right">TransactionTypeCode</td>
				<td align="left">: <? //echo $transactionTypeCode;?></td>
			</tr>
			<tr>
				<td align="right">TransactionId</td>
				<td align="left">: <? //echo $transactionId;?></td>
			</tr>

			<tr>
				<td align="right">Amount</td>
				<td align="left">: <? //echo $amount;?></td>
			</tr>
			<tr>
				<td align="right">Exponent</td>
				<td align="left">: <? //echo $exponent;?></td>
			</tr>
			<tr>
				<td align="right">CurrencyCode</td>
				<td align="left">: <? //echo $currencyCode;?></td>
			</tr>
			<tr>
				<td align="right">MerchantReferenceNo</td>
				<td align="left">: </td>
			</tr>

			<tr>
				<td align="right">Status</td>
				<td align="left">: <? //echo $status;?></td>
			</tr>
			<tr>
				<td align="right">3dsEci</td>
				<td align="left">: <? //echo $eci;?></td>
			</tr>
			<tr>
				<td align="right">PG ErrorCode</td>
				<td align="left">: <? //echo $pgErrorCode;?></td>
			</tr>

			<tr>
				<td align="right">PG ErrorDetail</td>
				<td align="left">: <? //echo $pgErrorDetail;?></td>
			</tr>
			<tr>
				<td align="right">PG ErrorMsg</td>
				<td align="left">: <? //echo $pgErrorMsg;?></td>
			</tr>-->
								 
		
	<tr > 
		<td valign="top" align="center"  colspan="2">
			<a href="http://www.supersavings.lk/index.php/">Buy Again</a>
		</td>
	</tr>
	</table>
</center>
</body>
</html>

